services:
  - type: web
    name: solar-invoice
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wkhtmltopdf xvfb python3-dev build-essential && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_ENV
        value: production